// <auto-generated />
using System;
using Confluences.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace IdentityServerAspNetIdentity.Migrations
{
    [DbContext(typeof(ConfluencesDbContext))]
    [Migration("20251203094133_AddSessionReportsTable")]
    partial class AddSessionReportsTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Confluences.Domain.Entities.AnnouncePage", b =>
                {
                    b.Property<int>("AnnouncePageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AnnouncePageId"));

                    b.Property<string>("AnnouncePageName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActivated")
                        .HasColumnType("boolean");

                    b.HasKey("AnnouncePageId");

                    b.ToTable("AnnouncePages");
                });

            modelBuilder.Entity("Confluences.Domain.Entities.AnnouncePageLink", b =>
                {
                    b.Property<int>("AnnouncePageLinkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AnnouncePageLinkId"));

                    b.Property<int>("AnnouncePageId")
                        .HasColumnType("integer");

                    b.Property<string>("AnnouncePageLinkLanguage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AnnouncePageLinkName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("AnnouncePageLinkId");

                    b.HasIndex("AnnouncePageId");

                    b.ToTable("AnnouncePageLinks");
                });

            modelBuilder.Entity("Confluences.Domain.Entities.ApplicationRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Confluences.Domain.Entities.ApplicationRoleClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Confluences.Domain.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<short>("GenderId")
                        .HasColumnType("smallint");

                    b.Property<bool>("HasSeenHelpVideo")
                        .HasColumnType("boolean");

                    b.Property<string>("Language")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nationality")
                        .HasColumnType("text");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PathImage")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<int?>("TypeAffiliationId")
                        .HasColumnType("integer");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("WantsMoreHomeworks")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("GenderId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.HasIndex("TypeAffiliationId");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Confluences.Domain.Entities.ApplicationUserClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Confluences.Domain.Entities.ApplicationUserLogin", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Confluences.Domain.Entities.ApplicationUserRole", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Confluences.Domain.Entities.ApplicationUserToken", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Confluences.Domain.Entities.Appointment", b =>
                {
                    b.Property<int>("AppointmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AppointmentId"));

                    b.Property<string>("AppointmentName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DateEnd")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DateStart")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsWeekly")
                        .HasColumnType("boolean");

                    b.Property<string>("TeacherId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("AppointmentId");

                    b.HasIndex("TeacherId");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("Confluences.Domain.Entities.AppointmentStudent", b =>
                {
                    b.Property<int>("AppointmentStudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AppointmentStudentId"));

                    b.Property<int>("AppointmentId")
                        .HasColumnType("integer");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("AppointmentStudentId");

                    b.HasIndex("AppointmentId");

                    b.HasIndex("StudentId");

                    b.ToTable("AppointmentStudents");
                });

            modelBuilder.Entity("Confluences.Domain.Entities.Contact", b =>
                {
                    b.Property<int>("ContactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ContactId"));

                    b.Property<string>("CreateurId")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DateCreation")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("EntrepriseId")
                        .HasColumnType("integer");

                    b.Property<string>("Fonction")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ModificateurId")
                        .HasColumnType("text");

                    b.Property<string>("Natel")
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.Property<string>("Nom")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Prenom")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TelFix")
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.HasKey("ContactId");

                    b.HasIndex("CreateurId");

                    b.HasIndex("EntrepriseId");

                    b.HasIndex("ModificateurId");

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("Confluences.Domain.Entities.Entreprise", b =>
                {
                    b.Property<int>("EntrepriseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EntrepriseId"));

                    b.Property<string>("Adr1")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Adr2")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CodePostal")
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)");

                    b.Property<string>("CreateurId")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DateCreation")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DateDernierContact")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DateLastRecall")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("FormateurIdDernierContact")
                        .HasColumnType("text");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Remarque")
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)");

                    b.Property<string>("StagiaireIdDernierContact")
                        .HasColumnType("text");

                    b.Property<string>("TelFix")
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.Property<string>("TelNatel")
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.Property<int?>("TypeEntrepriseId")
                        .HasColumnType("integer");

                    b.Property<int?>("TypeMoyenId")
                        .HasColumnType("integer");

                    b.Property<string>("Ville")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("EntrepriseId");

                    b.HasIndex("CreateurId");

                    b.HasIndex("FormateurIdDernierContact");

                    b.HasIndex("StagiaireIdDernierContact");

                    b.HasIndex("TypeEntrepriseId");

                    b.HasIndex("TypeMoyenId");

                    b.ToTable("Entreprises");
                });

            modelBuilder.Entity("Confluences.Domain.Entities.EntrepriseDomaine", b =>
                {
                    b.Property<int>("EntrepriseId")
                        .HasColumnType("integer");

                    b.Property<int>("TypeDomaineId")
                        .HasColumnType("integer");

                    b.HasKey("EntrepriseId", "TypeDomaineId");

                    b.HasIndex("TypeDomaineId");

                    b.ToTable("EntrepriseDomaines");
                });

            modelBuilder.Entity("Confluences.Domain.Entities.EntrepriseMetier", b =>
                {
                    b.Property<int>("EntrepriseId")
                        .HasColumnType("integer");

                    b.Property<int>("TypeMetierId")
                        .HasColumnType("integer");

                    b.HasKey("EntrepriseId", "TypeMetierId");

                    b.HasIndex("TypeMetierId");

                    b.ToTable("EntrepriseMetiers");
                });

            modelBuilder.Entity("Confluences.Domain.Entities.EntrepriseOffre", b =>
                {
                    b.Property<int>("EntrepriseId")
                        .HasColumnType("integer");

                    b.Property<int>("TypeOffreId")
                        .HasColumnType("integer");

                    b.HasKey("EntrepriseId", "TypeOffreId");

                    b.HasIndex("TypeOffreId");

                    b.ToTable("EntrepriseOffres");
                });

            modelBuilder.Entity("Confluences.Domain.Entities.Exercice", b =>
                {
                    b.Property<int>("ExerciceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ExerciceId"));

                    b.Property<string>("AudioLink")
                        .HasColumnType("text");

                    b.Property<string>("AudioLinkSecond")
                        .HasColumnType("text");

                    b.Property<string>("AudioLinkThird")
                        .HasColumnType("text");

                    b.Property<DateTime>("CorrectionDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CorrectionLink")
                        .HasColumnType("text");

                    b.Property<DateTime>("ExerciceDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ExerciceLink")
                        .HasColumnType("text");

                    b.Property<string>("ExerciceName")
                        .HasColumnType("text");

                    b.Property<bool>("IsHomeworkAdditionnal")
                        .HasColumnType("boolean");

                    b.Property<string>("TeacherId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TheoryId")
                        .HasColumnType("integer");

                    b.Property<string>("VideoLink")
                        .HasColumnType("text");

                    b.HasKey("ExerciceId");

                    b.HasIndex("TeacherId");

                    b.HasIndex("TheoryId");

                    b.ToTable("Exercices");
                });

            modelBuilder.Entity("Confluences.Domain.Entities.ExerciceAlone", b =>
                {
                    b.Property<int>("ExerciceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ExerciceId"));

                    b.Property<string>("AudioLink")
                        .HasColumnType("text");

                    b.Property<string>("AudioLinkSecond")
                        .HasColumnType("text");

                    b.Property<string>("AudioLinkThird")
                        .HasColumnType("text");

                    b.Property<DateTime>("CorrectionDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CorrectionLink")
                        .HasColumnType("text");

                    b.Property<DateTime>("ExerciceDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ExerciceLink")
                        .HasColumnType("text");

                    b.Property<string>("ExerciceName")
                        .HasColumnType("text");

                    b.Property<int>("HomeworkV2Id")
                        .HasColumnType("integer");

                    b.Property<bool>("IsHomeworkAdditionnal")
                        .HasColumnType("boolean");

                    b.Property<string>("TeacherId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VideoLink")
                        .HasColumnType("text");

                    b.HasKey("ExerciceId");

                    b.HasIndex("HomeworkV2Id");

                    b.HasIndex("TeacherId");

                    b.ToTable("ExercicesAlone");
                });

            modelBuilder.Entity("Confluences.Domain.Entities.Gender", b =>
                {
                    b.Property<short>("GenderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("GenderId"));

                    b.Property<string>("GenderName")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("GenderId");

                    b.ToTable("Genders");
                });

            modelBuilder.Entity("Confluences.Domain.Entities.HomeworkType", b =>
                {
                    b.Property<int>("HomeworkTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("HomeworkTypeId"));

                    b.Property<int>("HomeworkOrder")
                        .HasColumnType("integer");

                    b.Property<string>("HomeworkTypeName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("HomeworkTypeId");

                    b.ToTable("HomeworkTypes");
                });

            modelBuilder.Entity("Confluences.Domain.Entities.HomeworkV2", b =>
                {
                    b.Property<int>("HomeworkV2Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("HomeworkV2Id"));

                    b.Property<int>("HomeworkTypeId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("HomeworkV2Date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("HomeworkV2Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsFutur")
                        .HasColumnType("boolean");

                    b.Property<int>("SessionId")
                        .HasColumnType("integer");

                    b.Property<string>("TeacherId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("HomeworkV2Id");

                    b.HasIndex("HomeworkTypeId");

                    b.HasIndex("SessionId");

                    b.HasIndex("TeacherId");

                    b.ToTable("HomeworkV2s");
                });

            modelBuilder.Entity("Confluences.Domain.Entities.HomeworkV2Student", b =>
                {
                    b.Property<int>("HomeworkV2StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("HomeworkV2StudentId"));

                    b.Property<int>("ExerciceId")
                        .HasColumnType("integer");

                    b.Property<string>("HomeworkCommentaryTeacher")
                        .HasColumnType("text");

                    b.Property<string>("HomeworkFile")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HomeworkFileName")
                        .HasColumnType("text");

                    b.Property<string>("HomeworkFileSize")
                        .HasColumnType("text");

                    b.Property<string>("HomeworkFileTeacher")
                        .HasColumnType("text");

                    b.Property<string>("HomeworkFileType")
                        .HasColumnType("text");

                    b.Property<DateTime>("HomeworkStudentDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("HomeworkV2StudentId");

                    b.HasIndex("ExerciceId");

                    b.HasIndex("StudentId");

                    b.ToTable("HomeworkV2Students");
                });

            modelBuilder.Entity("Confluences.Domain.Entities.HomeworkV2StudentExerciceAlone", b =>
                {
                    b.Property<int>("HomeworkV2StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("HomeworkV2StudentId"));

                    b.Property<int>("ExerciceId")
                        .HasColumnType("integer");

                    b.Property<string>("HomeworkCommentaryTeacher")
                        .HasColumnType("text");

                    b.Property<string>("HomeworkFile")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HomeworkFileName")
                        .HasColumnType("text");

                    b.Property<string>("HomeworkFileSize")
                        .HasColumnType("text");

                    b.Property<string>("HomeworkFileTeacher")
                        .HasColumnType("text");

                    b.Property<string>("HomeworkFileType")
                        .HasColumnType("text");

                    b.Property<DateTime>("HomeworkStudentDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("HomeworkV2StudentId");

                    b.HasIndex("ExerciceId");

                    b.HasIndex("StudentId");

                    b.ToTable("HomeworkV2StudentExerciceAlones");
                });

            modelBuilder.Entity("Confluences.Domain.Entities.JobSearchAssistance", b =>
                {
                    b.Property<int>("JobSearchAssistanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("JobSearchAssistanceId"));

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("KeyWords")
                        .HasColumnType("text");

                    b.Property<string>("Town")
                        .HasColumnType("text");

                    b.Property<int?>("TypeJobSearchAssistanceId")
                        .HasColumnType("integer");

                    b.Property<int?>("TypeJobSearchAssistanceOccurrenceId")
                        .HasColumnType("integer");

                    b.Property<string>("Website")
                        .HasColumnType("text");

                    b.Property<string>("ZipCode")
                        .HasColumnType("text");

                    b.HasKey("JobSearchAssistanceId");

                    b.HasIndex("TypeJobSearchAssistanceId");

                    b.HasIndex("TypeJobSearchAssistanceOccurrenceId");

                    b.ToTable("JobSearchAssistances");
                });

            modelBuilder.Entity("Confluences.Domain.Entities.LastContact", b =>
                {
                    b.Property<int>("LastContactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LastContactId"));

                    b.Property<DateTime?>("DateOfContact")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("EntrepriseId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LastContactId");

                    b.HasIndex("EntrepriseId");

                    b.ToTable("LastContacts");
                });

            modelBuilder.Entity("Confluences.Domain.Entities.Presence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("StageId")
                        .HasColumnType("integer");

                    b.Property<string>("StagiaireId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.HasKey("Id");

                    b.HasIndex("StageId");

                    b.HasIndex("StagiaireId", "Date")
                        .IsUnique();

                    b.ToTable("Presences", (string)null);
                });

            modelBuilder.Entity("Confluences.Domain.Entities.SchoolClassRoom", b =>
                {
                    b.Property<int>("SchoolClassRoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SchoolClassRoomId"));

                    b.Property<string>("ExplanationVideoLink")
                        .HasColumnType("text");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<string>("SchoolClassRoomName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("SchoolClassRoomId");

                    b.ToTable("SchoolClassRooms");
                });

            modelBuilder.Entity("Confluences.Domain.Entities.SchoolClassRoomExplanation", b =>
                {
                    b.Property<int>("SchoolClassRoomExplanationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SchoolClassRoomExplanationId"));

                    b.Property<string>("AudioLink")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LanguageName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SchoolClassRoomId")
                        .HasColumnType("integer");

                    b.HasKey("SchoolClassRoomExplanationId");

                    b.HasIndex("SchoolClassRoomId");

                    b.ToTable("SchoolClassRoomExplanations");
                });

            modelBuilder.Entity("Confluences.Domain.Entities.Session", b =>
                {
                    b.Property<int>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SessionId"));

                    b.Property<DateTime>("DateEnd")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DateStart")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("SchoolClassRoomId")
                        .HasColumnType("integer");

                    b.Property<int>("SessionNumberId")
                        .HasColumnType("integer");

                    b.HasKey("SessionId");

                    b.HasIndex("SchoolClassRoomId");

                    b.HasIndex("SessionNumberId");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("Confluences.Domain.Entities.SessionNumber", b =>
                {
                    b.Property<int>("SessionNumberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SessionNumberId"));

                    b.HasKey("SessionNumberId");

                    b.ToTable("SessionNumbers");
                });

            modelBuilder.Entity("Confluences.Domain.Entities.SessionReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("EvaluationText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FollowUpActions")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("GlobalRate")
                        .HasColumnType("double precision");

                    b.Property<string>("Quarter")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StagiaireId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WorkshopsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StagiaireId");

                    b.ToTable("SessionReports");
                });

            modelBuilder.Entity("Confluences.Domain.Entities.SessionStudent", b =>
                {
                    b.Property<int>("SessionId")
                        .HasColumnType("integer");

                    b.Property<string>("StudentId")
                        .HasColumnType("text");

                    b.HasKey("SessionId", "StudentId");

                    b.HasIndex("StudentId");

                    b.ToTable("SessionStudents");
                });

            modelBuilder.Entity("Confluences.Domain.Entities.SessionTeacher", b =>
                {
                    b.Property<int>("SessionId")
                        .HasColumnType("integer");

                    b.Property<string>("TeacherId")
                        .HasColumnType("text");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.HasKey("SessionId", "TeacherId");

                    b.HasIndex("TeacherId");

                    b.ToTable("SessionTeachers");
                });

            modelBuilder.Entity("Confluences.Domain.Entities.Stage", b =>
                {
                    b.Property<int>("StageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("StageId"));

                    b.Property<string>("ActionSuivi")
                        .HasColumnType("text");

                    b.Property<bool?>("Attestation")
                        .HasColumnType("boolean");

                    b.Property<string>("Bilan")
                        .HasColumnType("text");

                    b.Property<string>("CreateurId")
                        .HasColumnType("text");

                    b.Property<DateTime>("Debut")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("EntrepriseId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("Fin")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool?>("HasContract")
                        .HasColumnType("boolean");

                    b.Property<string>("HoraireApresMidi")
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)");

                    b.Property<string>("HoraireMatin")
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)");

                    b.Property<string>("HoraireSamedi")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<bool?>("Rapport")
                        .HasColumnType("boolean");

                    b.Property<string>("Remarque")
                        .HasColumnType("text");

                    b.Property<bool?>("Repas")
                        .HasColumnType("boolean");

                    b.Property<int?>("SessionId")
                        .HasColumnType("integer");

                    b.Property<string>("StagiaireId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool?>("Trajets")
                        .HasColumnType("boolean");

                    b.Property<int?>("TypeAnnonceId")
                        .HasColumnType("integer");

                    b.Property<int>("TypeIntershipActivityId")
                        .HasColumnType("integer");

                    b.Property<int>("TypeMetierId")
                        .HasColumnType("integer");

                    b.Property<int?>("TypeStageId")
                        .HasColumnType("integer");

                    b.HasKey("StageId");

                    b.HasIndex("CreateurId");

                    b.HasIndex("EntrepriseId");

                    b.HasIndex("SessionId");

                    b.HasIndex("StagiaireId");

                    b.HasIndex("TypeAnnonceId");

                    b.HasIndex("TypeIntershipActivityId");

                    b.HasIndex("TypeMetierId");

                    b.HasIndex("TypeStageId");

                    b.ToTable("Stages");
                });

            modelBuilder.Entity("Confluences.Domain.Entities.StageFile", b =>
                {
                    b.Property<int>("StageFileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("StageFileId"));

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StageId")
                        .HasColumnType("integer");

                    b.HasKey("StageFileId");

                    b.HasIndex("StageId");

                    b.ToTable("StageFiles");
                });

            modelBuilder.Entity("Confluences.Domain.Entities.Theory", b =>
                {
                    b.Property<int>("TheoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TheoryId"));

                    b.Property<string>("AudioLink")
                        .HasColumnType("text");

                    b.Property<string>("AudioLinkSecond")
                        .HasColumnType("text");

                    b.Property<string>("AudioLinkThird")
                        .HasColumnType("text");

                    b.Property<int>("HomeworkV2Id")
                        .HasColumnType("integer");

                    b.Property<string>("TeacherId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("TheoryDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("TheoryLink")
                        .HasColumnType("text");

                    b.Property<string>("TheoryName")
                        .HasColumnType("text");

                    b.Property<string>("VideoLink")
                        .HasColumnType("text");

                    b.HasKey("TheoryId");

                    b.HasIndex("HomeworkV2Id");

                    b.HasIndex("TeacherId");

                    b.ToTable("Theories");
                });

            modelBuilder.Entity("Confluences.Domain.Entities.TypeAffiliation", b =>
                {
                    b.Property<int>("TypeAffiliationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TypeAffiliationId"));

                    b.Property<string>("Code")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Libelle")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("TypeAffiliationId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Libelle")
                        .IsUnique();

                    b.ToTable("TypeAffiliations");
                });

            modelBuilder.Entity("Confluences.Domain.Entities.TypeAnnonce", b =>
                {
                    b.Property<int>("TypeAnnonceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TypeAnnonceId"));

                    b.Property<string>("Libelle")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("TypeAnnonceId");

                    b.HasIndex("Libelle")
                        .IsUnique();

                    b.ToTable("TypeAnnonces");
                });

            modelBuilder.Entity("Confluences.Domain.Entities.TypeDomaine", b =>
                {
                    b.Property<int>("TypeDomaineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TypeDomaineId"));

                    b.Property<string>("Libelle")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("OldNames")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("TypeDomaineId");

                    b.HasIndex("Libelle")
                        .IsUnique();

                    b.ToTable("TypeDomaines");
                });

            modelBuilder.Entity("Confluences.Domain.Entities.TypeEntreprise", b =>
                {
                    b.Property<int>("TypeEntrepriseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TypeEntrepriseId"));

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("TypeEntrepriseId");

                    b.HasIndex("Nom")
                        .IsUnique();

                    b.ToTable("TypeEntreprises");
                });

            modelBuilder.Entity("Confluences.Domain.Entities.TypeIntershipActivity", b =>
                {
                    b.Property<int>("TypeIntershipActivityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TypeIntershipActivityId"));

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("TypeIntershipActivityId");

                    b.ToTable("TypeIntershipActivities");
                });

            modelBuilder.Entity("Confluences.Domain.Entities.TypeJobSearchAssistance", b =>
                {
                    b.Property<int>("TypeJobSearchAssistanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TypeJobSearchAssistanceId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("TypeJobSearchAssistanceId");

                    b.ToTable("TypeJobSearchAssistances");
                });

            modelBuilder.Entity("Confluences.Domain.Entities.TypeJobSearchAssistanceOccurrence", b =>
                {
                    b.Property<int>("TypeJobSearchAssistanceOccurrenceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TypeJobSearchAssistanceOccurrenceId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("TypeJobSearchAssistanceOccurrenceId");

                    b.ToTable("TypeJobSearchAssistanceOccurrences");
                });

            modelBuilder.Entity("Confluences.Domain.Entities.TypeMetier", b =>
                {
                    b.Property<int>("TypeMetierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TypeMetierId"));

                    b.Property<string>("Libelle")
                        .HasColumnType("text");

                    b.Property<string>("OldNames")
                        .HasColumnType("text");

                    b.HasKey("TypeMetierId");

                    b.HasIndex("Libelle")
                        .IsUnique();

                    b.ToTable("TypeMetiers");
                });

            modelBuilder.Entity("Confluences.Domain.Entities.TypeMoyen", b =>
                {
                    b.Property<int>("TypeMoyenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TypeMoyenId"));

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("TypeMoyenId");

                    b.HasIndex("Libelle")
                        .IsUnique();

                    b.ToTable("TypeMoyens");
                });

            modelBuilder.Entity("Confluences.Domain.Entities.TypeOffre", b =>
                {
                    b.Property<int>("TypeOffreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TypeOffreId"));

                    b.Property<string>("Libelle")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("TypeOffreId");

                    b.HasIndex("Libelle")
                        .IsUnique();

                    b.ToTable("TypeOffres");
                });

            modelBuilder.Entity("Confluences.Domain.Entities.TypeStage", b =>
                {
                    b.Property<int>("TypeStageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TypeStageId"));

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("TypeStageId");

                    b.HasIndex("Nom")
                        .IsUnique();

                    b.ToTable("TypeStages");
                });

            modelBuilder.Entity("Confluences.Domain.Entities.Views.Ressource", b =>
                {
                    b.Property<DateTime?>("Date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("HomeworkTypeName")
                        .HasColumnType("text");

                    b.Property<int?>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("RessourceType")
                        .HasColumnType("text");

                    b.Property<string>("SessionNumber")
                        .HasColumnType("text");

                    b.Property<string>("Teacher")
                        .HasColumnType("text");

                    b.ToTable("ressources");
                });

            modelBuilder.Entity("Confluences.Domain.Entities.AnnouncePageLink", b =>
                {
                    b.HasOne("Confluences.Domain.Entities.AnnouncePage", "AnnouncePage")
                        .WithMany()
                        .HasForeignKey("AnnouncePageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnnouncePage");
                });

            modelBuilder.Entity("Confluences.Domain.Entities.ApplicationRoleClaim", b =>
                {
                    b.HasOne("Confluences.Domain.Entities.ApplicationRole", "Role")
                        .WithMany("RoleClaims")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Confluences.Domain.Entities.ApplicationUser", b =>
                {
                    b.HasOne("Confluences.Domain.Entities.Gender", "Gender")
                        .WithMany()
                        .HasForeignKey("GenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Confluences.Domain.Entities.TypeAffiliation", "TypeAffiliation")
                        .WithMany("Users")
                        .HasForeignKey("TypeAffiliationId");

                    b.Navigation("Gender");

                    b.Navigation("TypeAffiliation");
                });

            modelBuilder.Entity("Confluences.Domain.Entities.ApplicationUserClaim", b =>
                {
                    b.HasOne("Confluences.Domain.Entities.ApplicationUser", "User")
                        .WithMany("Claims")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Confluences.Domain.Entities.ApplicationUserLogin", b =>
                {
                    b.HasOne("Confluences.Domain.Entities.ApplicationUser", "User")
                        .WithMany("Logins")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Confluences.Domain.Entities.ApplicationUserRole", b =>
                {
                    b.HasOne("Confluences.Domain.Entities.ApplicationRole", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Confluences.Domain.Entities.ApplicationUser", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Confluences.Domain.Entities.ApplicationUserToken", b =>
                {
                    b.HasOne("Confluences.Domain.Entities.ApplicationUser", "User")
                        .WithMany("Tokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Confluences.Domain.Entities.Appointment", b =>
                {
                    b.HasOne("Confluences.Domain.Entities.ApplicationUser", "Teacher")
                        .WithMany("Appointments")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("Confluences.Domain.Entities.AppointmentStudent", b =>
                {
                    b.HasOne("Confluences.Domain.Entities.Appointment", "Appointment")
                        .WithMany("AppointmentStudents")
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Confluences.Domain.Entities.ApplicationUser", "Student")
                        .WithMany("AppointmentStudents")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Appointment");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Confluences.Domain.Entities.Contact", b =>
                {
                    b.HasOne("Confluences.Domain.Entities.ApplicationUser", "Createur")
                        .WithMany("ContactCreateurs")
                        .HasForeignKey("CreateurId");

                    b.HasOne("Confluences.Domain.Entities.Entreprise", "Entreprise")
                        .WithMany("Contacts")
                        .HasForeignKey("EntrepriseId");

                    b.HasOne("Confluences.Domain.Entities.ApplicationUser", "ContactModificateur")
                        .WithMany("ContactModificateurs")
                        .HasForeignKey("ModificateurId");

                    b.Navigation("ContactModificateur");

                    b.Navigation("Createur");

                    b.Navigation("Entreprise");
                });

            modelBuilder.Entity("Confluences.Domain.Entities.Entreprise", b =>
                {
                    b.HasOne("Confluences.Domain.Entities.ApplicationUser", "Createur")
                        .WithMany("EntreprisCreateurs")
                        .HasForeignKey("CreateurId");

                    b.HasOne("Confluences.Domain.Entities.ApplicationUser", "FormateurDernierContact")
                        .WithMany("EntreprisFormateurIdDernierContacts")
                        .HasForeignKey("FormateurIdDernierContact");

                    b.HasOne("Confluences.Domain.Entities.ApplicationUser", "StagiaireDernier")
                        .WithMany("EntreprisStagiaireIdDernierContactNavigations")
                        .HasForeignKey("StagiaireIdDernierContact");

                    b.HasOne("Confluences.Domain.Entities.TypeEntreprise", "TypeEntreprise")
                        .WithMany("Entreprise")
                        .HasForeignKey("TypeEntrepriseId");

                    b.HasOne("Confluences.Domain.Entities.TypeMoyen", "TypeMoyen")
                        .WithMany("Entreprise")
                        .HasForeignKey("TypeMoyenId");

                    b.Navigation("Createur");

                    b.Navigation("FormateurDernierContact");

                    b.Navigation("StagiaireDernier");

                    b.Navigation("TypeEntreprise");

                    b.Navigation("TypeMoyen");
                });

            modelBuilder.Entity("Confluences.Domain.Entities.EntrepriseDomaine", b =>
                {
                    b.HasOne("Confluences.Domain.Entities.Entreprise", "Entreprise")
                        .WithMany("EntrepriseDomaines")
                        .HasForeignKey("EntrepriseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Confluences.Domain.Entities.TypeDomaine", "TypeDomaine")
                        .WithMany("EntrepriseDomaines")
                        .HasForeignKey("TypeDomaineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entreprise");

                    b.Navigation("TypeDomaine");
                });

            modelBuilder.Entity("Confluences.Domain.Entities.EntrepriseMetier", b =>
                {
                    b.HasOne("Confluences.Domain.Entities.Entreprise", "Entreprise")
                        .WithMany("EntrepriseMetiers")
                        .HasForeignKey("EntrepriseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Confluences.Domain.Entities.TypeMetier", "TypeMetier")
                        .WithMany("EntrepriseMetiers")
                        .HasForeignKey("TypeMetierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entreprise");

                    b.Navigation("TypeMetier");
                });

            modelBuilder.Entity("Confluences.Domain.Entities.EntrepriseOffre", b =>
                {
                    b.HasOne("Confluences.Domain.Entities.Entreprise", "Entreprise")
                        .WithMany("EntrepriseOffres")
                        .HasForeignKey("EntrepriseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Confluences.Domain.Entities.TypeOffre", "TypeOffre")
                        .WithMany("EntrepriseOffres")
                        .HasForeignKey("TypeOffreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entreprise");

                    b.Navigation("TypeOffre");
                });

            modelBuilder.Entity("Confluences.Domain.Entities.Exercice", b =>
                {
                    b.HasOne("Confluences.Domain.Entities.ApplicationUser", "Teacher")
                        .WithMany("Exercices")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Confluences.Domain.Entities.Theory", "Theory")
                        .WithMany("Exercices")
                        .HasForeignKey("TheoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Teacher");

                    b.Navigation("Theory");
                });

            modelBuilder.Entity("Confluences.Domain.Entities.ExerciceAlone", b =>
                {
                    b.HasOne("Confluences.Domain.Entities.HomeworkV2", "HomeworkV2")
                        .WithMany("ExercicesAlones")
                        .HasForeignKey("HomeworkV2Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Confluences.Domain.Entities.ApplicationUser", "Teacher")
                        .WithMany("ExerciceAlones")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HomeworkV2");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("Confluences.Domain.Entities.HomeworkV2", b =>
                {
                    b.HasOne("Confluences.Domain.Entities.HomeworkType", "HomeworkType")
                        .WithMany()
                        .HasForeignKey("HomeworkTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Confluences.Domain.Entities.Session", "Session")
                        .WithMany("HomeworkV2s")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Confluences.Domain.Entities.ApplicationUser", "Teacher")
                        .WithMany("HomeworkV2s")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HomeworkType");

                    b.Navigation("Session");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("Confluences.Domain.Entities.HomeworkV2Student", b =>
                {
                    b.HasOne("Confluences.Domain.Entities.Exercice", "Exercice")
                        .WithMany("HomeworkV2students")
                        .HasForeignKey("ExerciceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Confluences.Domain.Entities.ApplicationUser", "Student")
                        .WithMany("HomeworkV2Students")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercice");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Confluences.Domain.Entities.HomeworkV2StudentExerciceAlone", b =>
                {
                    b.HasOne("Confluences.Domain.Entities.ExerciceAlone", "ExerciceAlone")
                        .WithMany("HomeworkV2StudentExerciceAlones")
                        .HasForeignKey("ExerciceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Confluences.Domain.Entities.ApplicationUser", "Student")
                        .WithMany("HomeworkV2StudentExerciceAlones")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExerciceAlone");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Confluences.Domain.Entities.JobSearchAssistance", b =>
                {
                    b.HasOne("Confluences.Domain.Entities.TypeJobSearchAssistance", "TypeJobSearchAssistance")
                        .WithMany("JobSearchAssistances")
                        .HasForeignKey("TypeJobSearchAssistanceId");

                    b.HasOne("Confluences.Domain.Entities.TypeJobSearchAssistanceOccurrence", "TypeJobSearchAssistanceOccurrence")
                        .WithMany("JobSearchAssistances")
                        .HasForeignKey("TypeJobSearchAssistanceOccurrenceId");

                    b.Navigation("TypeJobSearchAssistance");

                    b.Navigation("TypeJobSearchAssistanceOccurrence");
                });

            modelBuilder.Entity("Confluences.Domain.Entities.LastContact", b =>
                {
                    b.HasOne("Confluences.Domain.Entities.Entreprise", "Entreprise")
                        .WithMany("LastContacts")
                        .HasForeignKey("EntrepriseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entreprise");
                });

            modelBuilder.Entity("Confluences.Domain.Entities.Presence", b =>
                {
                    b.HasOne("Confluences.Domain.Entities.Stage", "Stage")
                        .WithMany()
                        .HasForeignKey("StageId");

                    b.HasOne("Confluences.Domain.Entities.ApplicationUser", "Stagiaire")
                        .WithMany()
                        .HasForeignKey("StagiaireId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stage");

                    b.Navigation("Stagiaire");
                });

            modelBuilder.Entity("Confluences.Domain.Entities.SchoolClassRoomExplanation", b =>
                {
                    b.HasOne("Confluences.Domain.Entities.SchoolClassRoom", "SchoolClassRoom")
                        .WithMany("SchoolClassRoomExplanations")
                        .HasForeignKey("SchoolClassRoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SchoolClassRoom");
                });

            modelBuilder.Entity("Confluences.Domain.Entities.Session", b =>
                {
                    b.HasOne("Confluences.Domain.Entities.SchoolClassRoom", "SchoolClassRoom")
                        .WithMany("Sessions")
                        .HasForeignKey("SchoolClassRoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Confluences.Domain.Entities.SessionNumber", "SessionNumber")
                        .WithMany()
                        .HasForeignKey("SessionNumberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SchoolClassRoom");

                    b.Navigation("SessionNumber");
                });

            modelBuilder.Entity("Confluences.Domain.Entities.SessionReport", b =>
                {
                    b.HasOne("Confluences.Domain.Entities.ApplicationUser", "Stagiaire")
                        .WithMany()
                        .HasForeignKey("StagiaireId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stagiaire");
                });

            modelBuilder.Entity("Confluences.Domain.Entities.SessionStudent", b =>
                {
                    b.HasOne("Confluences.Domain.Entities.Session", "Session")
                        .WithMany("SessionStudents")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Confluences.Domain.Entities.ApplicationUser", "Student")
                        .WithMany("SessionStudents")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Confluences.Domain.Entities.SessionTeacher", b =>
                {
                    b.HasOne("Confluences.Domain.Entities.Session", "Session")
                        .WithMany("SessionTeachers")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Confluences.Domain.Entities.ApplicationUser", "Teacher")
                        .WithMany("SessionTeachers")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("Confluences.Domain.Entities.Stage", b =>
                {
                    b.HasOne("Confluences.Domain.Entities.ApplicationUser", "Createur")
                        .WithMany("StageCreateurs")
                        .HasForeignKey("CreateurId");

                    b.HasOne("Confluences.Domain.Entities.Entreprise", "Entreprise")
                        .WithMany("Stages")
                        .HasForeignKey("EntrepriseId");

                    b.HasOne("Confluences.Domain.Entities.Session", "Session")
                        .WithMany("Stages")
                        .HasForeignKey("SessionId");

                    b.HasOne("Confluences.Domain.Entities.ApplicationUser", "Stagiaire")
                        .WithMany("StageStagiaires")
                        .HasForeignKey("StagiaireId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Confluences.Domain.Entities.TypeAnnonce", "TypeAnnonce")
                        .WithMany("Stages")
                        .HasForeignKey("TypeAnnonceId");

                    b.HasOne("Confluences.Domain.Entities.TypeIntershipActivity", "TypeIntershipActivity")
                        .WithMany("Stages")
                        .HasForeignKey("TypeIntershipActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Confluences.Domain.Entities.TypeMetier", "TypeMetier")
                        .WithMany("Stages")
                        .HasForeignKey("TypeMetierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Confluences.Domain.Entities.TypeStage", "TypeStage")
                        .WithMany("Stages")
                        .HasForeignKey("TypeStageId");

                    b.Navigation("Createur");

                    b.Navigation("Entreprise");

                    b.Navigation("Session");

                    b.Navigation("Stagiaire");

                    b.Navigation("TypeAnnonce");

                    b.Navigation("TypeIntershipActivity");

                    b.Navigation("TypeMetier");

                    b.Navigation("TypeStage");
                });

            modelBuilder.Entity("Confluences.Domain.Entities.StageFile", b =>
                {
                    b.HasOne("Confluences.Domain.Entities.Stage", "Stage")
                        .WithMany("StageFiles")
                        .HasForeignKey("StageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stage");
                });

            modelBuilder.Entity("Confluences.Domain.Entities.Theory", b =>
                {
                    b.HasOne("Confluences.Domain.Entities.HomeworkV2", "HomeworkV2")
                        .WithMany("Theories")
                        .HasForeignKey("HomeworkV2Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Confluences.Domain.Entities.ApplicationUser", "Teacher")
                        .WithMany("Theories")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HomeworkV2");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("Confluences.Domain.Entities.ApplicationRole", b =>
                {
                    b.Navigation("RoleClaims");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Confluences.Domain.Entities.ApplicationUser", b =>
                {
                    b.Navigation("AppointmentStudents");

                    b.Navigation("Appointments");

                    b.Navigation("Claims");

                    b.Navigation("ContactCreateurs");

                    b.Navigation("ContactModificateurs");

                    b.Navigation("EntreprisCreateurs");

                    b.Navigation("EntreprisFormateurIdDernierContacts");

                    b.Navigation("EntreprisStagiaireIdDernierContactNavigations");

                    b.Navigation("ExerciceAlones");

                    b.Navigation("Exercices");

                    b.Navigation("HomeworkV2StudentExerciceAlones");

                    b.Navigation("HomeworkV2Students");

                    b.Navigation("HomeworkV2s");

                    b.Navigation("Logins");

                    b.Navigation("SessionStudents");

                    b.Navigation("SessionTeachers");

                    b.Navigation("StageCreateurs");

                    b.Navigation("StageStagiaires");

                    b.Navigation("Theories");

                    b.Navigation("Tokens");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Confluences.Domain.Entities.Appointment", b =>
                {
                    b.Navigation("AppointmentStudents");
                });

            modelBuilder.Entity("Confluences.Domain.Entities.Entreprise", b =>
                {
                    b.Navigation("Contacts");

                    b.Navigation("EntrepriseDomaines");

                    b.Navigation("EntrepriseMetiers");

                    b.Navigation("EntrepriseOffres");

                    b.Navigation("LastContacts");

                    b.Navigation("Stages");
                });

            modelBuilder.Entity("Confluences.Domain.Entities.Exercice", b =>
                {
                    b.Navigation("HomeworkV2students");
                });

            modelBuilder.Entity("Confluences.Domain.Entities.ExerciceAlone", b =>
                {
                    b.Navigation("HomeworkV2StudentExerciceAlones");
                });

            modelBuilder.Entity("Confluences.Domain.Entities.HomeworkV2", b =>
                {
                    b.Navigation("ExercicesAlones");

                    b.Navigation("Theories");
                });

            modelBuilder.Entity("Confluences.Domain.Entities.SchoolClassRoom", b =>
                {
                    b.Navigation("SchoolClassRoomExplanations");

                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("Confluences.Domain.Entities.Session", b =>
                {
                    b.Navigation("HomeworkV2s");

                    b.Navigation("SessionStudents");

                    b.Navigation("SessionTeachers");

                    b.Navigation("Stages");
                });

            modelBuilder.Entity("Confluences.Domain.Entities.Stage", b =>
                {
                    b.Navigation("StageFiles");
                });

            modelBuilder.Entity("Confluences.Domain.Entities.Theory", b =>
                {
                    b.Navigation("Exercices");
                });

            modelBuilder.Entity("Confluences.Domain.Entities.TypeAffiliation", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Confluences.Domain.Entities.TypeAnnonce", b =>
                {
                    b.Navigation("Stages");
                });

            modelBuilder.Entity("Confluences.Domain.Entities.TypeDomaine", b =>
                {
                    b.Navigation("EntrepriseDomaines");
                });

            modelBuilder.Entity("Confluences.Domain.Entities.TypeEntreprise", b =>
                {
                    b.Navigation("Entreprise");
                });

            modelBuilder.Entity("Confluences.Domain.Entities.TypeIntershipActivity", b =>
                {
                    b.Navigation("Stages");
                });

            modelBuilder.Entity("Confluences.Domain.Entities.TypeJobSearchAssistance", b =>
                {
                    b.Navigation("JobSearchAssistances");
                });

            modelBuilder.Entity("Confluences.Domain.Entities.TypeJobSearchAssistanceOccurrence", b =>
                {
                    b.Navigation("JobSearchAssistances");
                });

            modelBuilder.Entity("Confluences.Domain.Entities.TypeMetier", b =>
                {
                    b.Navigation("EntrepriseMetiers");

                    b.Navigation("Stages");
                });

            modelBuilder.Entity("Confluences.Domain.Entities.TypeMoyen", b =>
                {
                    b.Navigation("Entreprise");
                });

            modelBuilder.Entity("Confluences.Domain.Entities.TypeOffre", b =>
                {
                    b.Navigation("EntrepriseOffres");
                });

            modelBuilder.Entity("Confluences.Domain.Entities.TypeStage", b =>
                {
                    b.Navigation("Stages");
                });
#pragma warning restore 612, 618
        }
    }
}
