START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251125095402_AddPresenceTable') THEN
    CREATE TABLE "Presences" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "StagiaireId" text NOT NULL,
        "Date" timestamp without time zone NOT NULL,
        "Statut" character varying(2) NOT NULL,
        "StageId" integer NULL,
        "CreatedAt" timestamp without time zone NOT NULL,
        "LastModifiedAt" timestamp without time zone NULL,
        CONSTRAINT "PK_Presences" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Presences_AspNetUsers_StagiaireId" FOREIGN KEY ("StagiaireId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_Presences_Stages_StageId" FOREIGN KEY ("StageId") REFERENCES "Stages" ("StageId")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251125095402_AddPresenceTable') THEN
    CREATE INDEX "IX_Presences_StageId" ON "Presences" ("StageId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251125095402_AddPresenceTable') THEN
    CREATE UNIQUE INDEX "IX_Presences_StagiaireId_Date" ON "Presences" ("StagiaireId", "Date");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251125095402_AddPresenceTable') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251125095402_AddPresenceTable', '6.0.9');
    END IF;
END $EF$;
COMMIT;

