START TRANSACTION;

CREATE TABLE "Presences" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "StagiaireId" text NOT NULL,
    "Date" timestamp without time zone NOT NULL,
    "Statut" character varying(2) NOT NULL,
    "StageId" integer NULL,
    "CreatedAt" timestamp without time zone NOT NULL,
    "LastModifiedAt" timestamp without time zone NULL,
    CONSTRAINT "PK_Presences" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Presences_AspNetUsers_StagiaireId" FOREIGN KEY ("StagiaireId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Presences_Stages_StageId" FOREIGN KEY ("StageId") REFERENCES "Stages" ("StageId")
);

CREATE INDEX "IX_Presences_StageId" ON "Presences" ("StageId");

CREATE UNIQUE INDEX "IX_Presences_StagiaireId_Date" ON "Presences" ("StagiaireId", "Date");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251125095402_AddPresenceTable', '6.0.9');

COMMIT;

